package io.brahmaos.samples.walletmanagersample;

import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.support.v7.widget.AppCompatCheckBox;
import android.util.Log;
import android.view.View;
import android.widget.Button;
import android.widget.CompoundButton;
import android.widget.EditText;
import android.widget.TextView;
import android.widget.Toast;

import java.io.File;
import java.math.BigInteger;
import java.util.List;

import brahmaos.app.WalletManager;
import brahmaos.content.BrahmaContext;
import brahmaos.content.WalletData;
import brahmaos.util.DataCryptoUtils;

/**
 * In this demo ethereum wallet address 0x4029a7e31ae310479784e9ade9e3172698807341 is for testing.
 * It is generated by the mnemonics:
 * "club case spatial pepper mercy flush staff fame utility twenty whip nasty".
 * Please firstly import this wallet aacount, and then test.
 *
 * **/
public class MainActivity extends AppCompatActivity {
    public static final String TAG = "WalletManagerSample";

    private EditText mEtCreateName, mEtCreatePassword;
    private Button mBtnCreate;

    private TextView mTvListAllWallets;
    private Button mBtnListAllWallets;

    private EditText mEtDeleteAddress;
    private Button mBtnDelete;

    private EditText mEtPrivateKey, mEtMnemonics, mEtKeyStore, mEtPassword;
    private Button mBtnImport;

    private EditText mEtUpdateAddress, mEtOldPwd, mEtNewPwd;
    private Button mBtnUpdateWallet;

    private EditText mEtBlanceAddress, mEtTokenAddress;
    private TextView mTvBlance;
    private Button mBtnGetBlance;

    private EditText mEtGasPrice, mEtGasLimit;
    private TextView mEtEtcHash, mEtKncHash;
    private Button mBtnTransfer, mBtnTransferToken;

    private EditText mEtEthTransHash;
    private TextView mTvEthTransaction;
    private Button mBtnEthTransaction;

    private WalletManager mWalletManager;
    private List<WalletData> mWalletList;


    private AppCompatCheckBox mUseTestUrl;
    private static final String ROPSTEN_URL = "https://ropsten.infura.io/Gy3Csyt4bzKIGsctm3g0";

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        mWalletManager = (WalletManager) getSystemService(BrahmaContext.WALLET_SERVICE);

        mEtCreateName = (EditText) findViewById(R.id.et_create_name);
        mEtCreatePassword = (EditText) findViewById(R.id.et_create_password);
        mEtDeleteAddress = (EditText) findViewById(R.id.et_delete_address);

        mEtPrivateKey = (EditText) findViewById(R.id.et_private_key);
        mEtMnemonics = (EditText) findViewById(R.id.et_mnemonics);
        mEtKeyStore = (EditText) findViewById(R.id.et_keyStore);
        mEtPassword = (EditText) findViewById(R.id.et_password);

        mEtUpdateAddress = (EditText) findViewById(R.id.et_update_address);
        mEtOldPwd = (EditText) findViewById(R.id.et_old_pwd);
        mEtNewPwd = (EditText) findViewById(R.id.et_new_pwd);

        mBtnCreate = (Button) findViewById(R.id.btn_create);
        mBtnCreate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        mWalletList = mWalletManager.createWallet(
                                mEtCreateName.getText().toString().trim(),
                                mEtCreatePassword.getText().toString().trim());
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                if (mWalletList != null) {
                                    Toast.makeText(MainActivity.this,
                                            "have created " + mWalletList.size() + " wallsts.", Toast.LENGTH_SHORT).show();
                                }
                                for (WalletData data : mWalletList) {
                                    String mnemonics = mWalletManager.decryptMnemonics(
                                            data.mnemonicStr, mEtCreatePassword.getText().toString().trim());
                                    Log.d(TAG, "mnemonics are: " + mnemonics);
                                }
                            }
                        });
                    }
                }).start();
            }
        });

        mBtnImport = (Button) findViewById(R.id.btn_import);
        mBtnImport.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (null == mEtPassword.getText()|| mEtPassword.getText().toString().isEmpty()) {
                    Toast.makeText(MainActivity.this, "Please input the password.", Toast.LENGTH_SHORT).show();
                    return;
                }
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        if (mEtPrivateKey.getText() != null && !mEtPrivateKey.getText().toString().isEmpty()) {
                            mWalletManager.importEthereumWallet(
                                    "importPK",
                                    mEtPassword.getText().toString().trim(),
                                    mEtPrivateKey.getText().toString().trim(),
                                    WalletManager.IMPORT_BY_PRIVATE_KEY);
                        } else if (mEtMnemonics.getText() != null && !mEtMnemonics.getText().toString().isEmpty()) {
                            mWalletManager.importEthereumWallet(
                                    "importMN",
                                    mEtPassword.getText().toString().trim(),
                                    mEtMnemonics.getText().toString().trim(),
                                    WalletManager.IMPORT_BY_MNEMONICS);
                        } else if (mEtKeyStore.getText() != null && !mEtKeyStore.getText().toString().isEmpty()) {
                            mWalletManager.importEthereumWallet(
                                    "importKS",
                                    mEtPassword.getText().toString().trim(),
                                    mEtKeyStore.getText().toString().trim(),
                                    WalletManager.IMPORT_BY_KEYSTORE);
                        } else {
                            runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                    Toast.makeText(MainActivity.this, "Please input the data.", Toast.LENGTH_SHORT).show();
                                }
                            });
                            return;
                        }
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(MainActivity.this, "Import completed.", Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                }).start();
            }
        });

        mBtnUpdateWallet = (Button) findViewById(R.id.btn_update_wallet);
        mBtnUpdateWallet.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        final int nameResult = mWalletManager.updateWalletNameForAddress("update" + System.currentTimeMillis(),
                                mEtUpdateAddress.getText().toString().trim());
                        final int passwordResult = mWalletManager.updateEthereumWalletPassword(
                                mEtUpdateAddress.getText().toString().trim(),
                                mEtOldPwd.getText().toString().trim(),
                                mEtNewPwd.getText().toString().trim());
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                Toast.makeText(MainActivity.this,nameResult + "; " + passwordResult, Toast.LENGTH_SHORT).show();
                            }
                        });
                    }
                }).start();
            }
        });

        mTvListAllWallets = (TextView) findViewById(R.id.tv_list_all);
        mBtnListAllWallets = (Button) findViewById(R.id.btn_list_all);
        mBtnListAllWallets.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mTvListAllWallets.setText("");
                List<WalletData> allWallets = mWalletManager.getAllWallets();
                if (null == allWallets || allWallets.isEmpty()) {
                    mTvListAllWallets.setText("has no wallet");
                } else {
                    for (WalletData wallet : allWallets) {
                        mTvListAllWallets.setText(mTvListAllWallets.getText().toString()
                                + wallet.address + ";\n");
                    }
                }

                List<WalletData> ethWallets =
                        mWalletManager.getWalletsForChainType(WalletManager.WALLET_CHAIN_TYPE_ETH);
                Log.d(TAG,"get " + (ethWallets == null ? "null" : ethWallets.size()) + "ETH wallets");
            }
        });

        mBtnDelete = (Button) findViewById(R.id.btn_delete);
        mBtnDelete.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                int res = mWalletManager.deleteWalletByAddress(mEtDeleteAddress.getText().toString().trim());
                Toast.makeText(MainActivity.this,
                        "deleted " + (res == WalletManager.CODE_NO_ERROR ? "success" : "failed"), Toast.LENGTH_SHORT).show();
            }
        });

        mUseTestUrl = (AppCompatCheckBox) findViewById(R.id.checkbox_use_test);
        mUseTestUrl.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
            @Override
            public void onCheckedChanged(CompoundButton compoundButton, boolean b) {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        final String ethGasPrice = mWalletManager.getEthereumGasPrice(
                                mUseTestUrl.isChecked() ? ROPSTEN_URL : null);
                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                if (null == ethGasPrice || ethGasPrice.isEmpty()) {
                                    mEtGasPrice.setText("error");
                                } else {
                                    mEtGasPrice.setText(ethGasPrice);
                                }
                            }
                        });
                    }
                }).start();
            }
        });

        mEtBlanceAddress = (EditText) findViewById(R.id.et_blance_address);
        mEtTokenAddress = (EditText) findViewById(R.id.et_token_address);
        mTvBlance = (TextView) findViewById(R.id.tv_blance);
        mBtnGetBlance = (Button) findViewById(R.id.btn_get_blance);
        mBtnGetBlance.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mTvBlance.setText("");
                //just for test
                String tokenAddr = mEtTokenAddress.getText() == null ? null : (mEtTokenAddress.getText().toString());
                if (tokenAddr != null) {
                    if ("KNC".equalsIgnoreCase(tokenAddr)) {
                        tokenAddr = "0x4E470dc7321E84CA96FcAEDD0C8aBCebbAEB68C6";
                    }
                    if ("BRM".equalsIgnoreCase(tokenAddr)) {
                        tokenAddr = "0xd7732e3783b0047aa251928960063f863ad022d8";
                    }
                }
                mWalletManager.getEthereumBalanceByAddress(
                        mUseTestUrl.isChecked() ? ROPSTEN_URL : null,
                        mEtBlanceAddress.getText().toString(),
                        tokenAddr,
                        new GetETHBlanceListener(""));

            }
        });

        mEtEtcHash = (TextView) findViewById(R.id.et_etc_hash);
        mEtKncHash = (TextView) findViewById(R.id.et_knc_hash);
        mEtGasPrice = (EditText) findViewById(R.id.et_gas_price);
        mEtGasLimit = (EditText) findViewById(R.id.et_gas_limit);
        //get gas price and update the edit text
        new Thread(new Runnable() {
            @Override
            public void run() {
                    final String ethGasPrice = mWalletManager.getEthereumGasPrice(
                            mUseTestUrl.isChecked() ? ROPSTEN_URL : null);
                    runOnUiThread(new Runnable() {
                        @Override
                        public void run() {
                            if (null == ethGasPrice || ethGasPrice.isEmpty()) {
                                mEtGasPrice.setText("error");
                            } else {
                                mEtGasPrice.setText(ethGasPrice);
                            }
                        }
                    });
            }
        }).start();


        mEtGasPrice.setText("20");
        mEtGasLimit.setText("400000");
        mBtnTransfer = (Button)findViewById(R.id.btn_transfer);
        mBtnTransfer.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                mBtnTransfer.setEnabled(false);
                mBtnTransferToken.setEnabled(false);
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        //ETH ropsten
                        final String etcHash = mWalletManager.transferEthereum(
                                mUseTestUrl.isChecked() ? ROPSTEN_URL : null,
                                "0x4029a7e31ae310479784e9ade9e3172698807341",
                                "",
                                "qqqqqq",
                                "0x62461ec66ea7014833181e8e22a8e64f40de34ec",
                                0.1,
                                 new BigInteger(mEtGasPrice.getText().toString().trim()).doubleValue(),
                                 Long.valueOf(mEtGasLimit.getText().toString().trim()),
                                "test");

                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                if (null == etcHash || etcHash.isEmpty()) {
                                    mEtEtcHash.setText("error");
                                } else {
                                    mEtEtcHash.setText(etcHash);
                                }
                                mBtnTransferToken.setEnabled(true);
                                mBtnTransfer.setEnabled(true);
                            }
                        });
                    }
                }).start();
            }
        });

        mBtnTransferToken = (Button) findViewById(R.id.btn_transfer_token);
        mBtnTransferToken.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                mBtnTransferToken.setEnabled(false);
                mBtnTransfer.setEnabled(false);
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        //KNC ropsten
                        final String kncHash = mWalletManager.transferEthereum(
                                mUseTestUrl.isChecked() ? ROPSTEN_URL : null,
                                "0x4029a7e31ae310479784e9ade9e3172698807341",
                                "0x4E470dc7321E84CA96FcAEDD0C8aBCebbAEB68C6",
                                "qqqqqq",
                                "0x62461ec66ea7014833181e8e22a8e64f40de34ec",
                                1,
                                 new BigInteger(mEtGasPrice.getText().toString().trim()).doubleValue(),
                                 Long.valueOf(mEtGasLimit.getText().toString().trim()),
                                "test");

                        runOnUiThread(new Runnable() {
                            @Override
                            public void run() {
                                if (null == kncHash || kncHash.isEmpty()) {
                                    mEtKncHash.setText("error");
                                } else {
                                    mEtKncHash.setText(kncHash);
                                }
                                mBtnTransfer.setEnabled(true);
                                mBtnTransferToken.setEnabled(true);
                            }
                        });
                    }
                }).start();
            }
        });

        mEtEthTransHash = (EditText) findViewById(R.id.et_trans_hash);
        mTvEthTransaction = (TextView) findViewById(R.id.tv_transaction);
        mBtnEthTransaction = (Button) findViewById(R.id.btn_transaction);
        mBtnEthTransaction.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                if (mEtEthTransHash.getText() != null &&
                        !mEtEthTransHash.getText().toString().isEmpty()) {
                    new Thread(new Runnable() {
                        @Override
                        public void run() {
                            final String result = mWalletManager.getEthereumTransactionByHash(
                                    mUseTestUrl.isChecked() ? ROPSTEN_URL : null,
                                    mEtEthTransHash.getText().toString().trim());
                            runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                    if (null ==result || result.isEmpty()) {
                                        mTvEthTransaction.setText("error");
                                    } else {
                                        mTvEthTransaction.setText(result);
                                    }
                                }
                            });
                        }
                    }).start();
                }
            }
        });
    }

    private class GetETHBlanceListener implements WalletManager.OnETHBlanceGetListener {
        private String mType;
        public GetETHBlanceListener(String type) {
            Log.d(TAG, "listener " + type);
            mType = type;
        }

        @Override
        public void onETHBlanceGetError() {
            Log.d(TAG, "onETHBlanceGetError---" + mType);
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    mTvBlance.setText(mTvBlance.getText().toString() + (mType + " error; "));
                }
            });
        }

        @Override
        public void onETHBlanceGetSuccess(String s) {
            final String text =((null == s || s.isEmpty())?"empty":s);
            Log.d(TAG, "onETHBlanceGetSuccess---" + mType + ": " + text);
            runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    mTvBlance.setText(mTvBlance.getText().toString() + (mType + " " + text + "; "));
                }
            });
        }
    }
}
